### ISSUE TITLE
Folding issue

### ISSUE THREAD

**Issue by cgestes** [laobubu/HyperMD#12]
When using the following markdown:

_You **can** combine them_

the folding is incorrect. 

It displays this:
![image](https://user-images.githubusercontent.com/49141/38416602-8080d1e2-3995-11e8-8bf1-6859696edb56.png)

**Comment by laobubu** [comment]
Hiding behavior is changed now, in order to improve the efficiency. Please try and feedback.

**Comment by cgestes** [comment]
awesome I will check. I didnt see the first notification :)

**Comment by cgestes** [comment]
it is fixed :)
