### ISSUE TITLE
Submit HyperMD to npm to enable fast references through CDNs

### ISSUE THREAD

**Issue by nokola** [laobubu/HyperMD#13]
Thanks for making this awesome markdown editor! Heads down the best I've seen so far, and I've seen 30+.

Do you have plans to add it to npm so that we can install it through jsdelivr's CDN? That would make it faster to load from different parts of the world and speed up adoption.

for example:
https://www.jsdelivr.com/?query=hypermd

**Comment by laobubu** [comment]
Maybe next version, with more user-friendly features. Won't take too long (I hope)

BTW, give requirejs a try, which works with jsdelivr too. (see demo/index.js and replace `...node_modules...` with your CDN URL prefix)

**Comment by nokola** [comment]
Thanks, will try!

**Comment by laobubu** [comment]
Just a reminder about requirejs and marked : if you're using requirejs, do not import marked with <script> tag. 

Code is updated and marked is now required module.

**Comment by nokola** [comment]
Thanks! I don't need "hover" addon for now, so ignored it. I just use direct script import for the moment for testing.

**Comment by laobubu** [comment]
Just uploaded v0.3.0 to npm: https://www.npmjs.com/package/hypermd

**Comment by nokola** [comment]
wohoo! Will try it out
