### ISSUE TITLE
Suggestion: Attach files with "frosted" preview similar to gmail

### ISSUE THREAD

**Issue by nokola** [laobubu/HyperMD#16]
I think gmail looks nicer because it shows preview of the file while uploading.
Would be good if HyperMD also does something similar:
1. Copy-paste image, during uploading see "frosted image" like this:
![image](https://user-images.githubusercontent.com/6869225/39635123-62127dea-4f71-11e8-99b4-4c01cca91314.png)

2. After upload the unfrosted image shows up:
![image](https://user-images.githubusercontent.com/6869225/39634956-fa0c0928-4f70-11e8-8026-b5f6be8f5086.png)

This will eliminate the need for the extra upload URL and also for blinking.

**Comment by laobubu** [comment]
Already implemented.
