### ISSUE TITLE
Feature: Allow drag-drop any file (.zip, .txt, .apk) not just image

### ISSUE THREAD

**Issue by nokola** [laobubu/HyperMD#17]
I think this will be a very good change for paste-image.

**Comment by laobubu** [comment]
Maybe drag'n'drop can be a standalone add-on :)

2018-05-04 23:22 GMT+08:00 Nokola <notifications@github.com>:

**Comment by nokola** [comment]
What about rename 'paste-image' to 'file-upload' and include all the paste, dragdrop, regular file functionality? Paste, drag and drop, also custom file share 95% common code, I think they are better as single add-on. Also as a user I always expect both paste and drag-drop to work, so it makes sense to keep them as one. What do you think?
