### ISSUE TITLE
表格渲染的问题

### ISSUE THREAD

**Issue by lorenwe** [laobubu/HyperMD#24]
表格里面渲染代码块是会有错位的,以及在表格里面的代码块无法换行，表格里面使用单  ` 符号代码块是没问题的，表格里面好像无法渲染列表,除此之外，这个编辑器简直完美，所写即所见

**Comment by lorenwe** [comment]
显示效果如下
![1526630891 1](https://user-images.githubusercontent.com/17443344/40223459-b530b2ea-5ab5-11e8-9462-35dfcb1251c5.jpg)

**Comment by laobubu** [comment]
现在代码在进行大重构，表格的实现方式换了。如果不出意外，会在下周合并到 master 分枝。

列表不应该放到表格里的。表格只支持单行的文本。

还剩 HideToken 没搞定。现在的大致效果如下：

```
| 表头 | 表头 | 表头 | 标题 |
| `Code`  | ~~删除~~ | *斜体字* |  ***粗体斜体混合*** |
| `var a = 1;` | [试试看链接](http://laobubu.net)| $ [\matrix { Begin \\ End }] $|![](https://codemirror.net/doc/logo.png) |
```

![default](https://user-images.githubusercontent.com/1373914/40235669-8c011c98-5add-11e8-98be-866a2aa590c3.png)

**Comment by laobubu** [comment]
至于 NPM 包，等重构完成以后就发布。
本来还要写一下使用文档的，估计没太多精力了，看情况吧。

**Comment by laobubu** [comment]
表格功能应该是实现完毕了。前面那种 orgmode 类似的格式已经不支持了：

```
| 表头 | 表头 | 表头 | 标题 |
| `Code`  | ~~删除~~ | *斜体字* |  ***粗体斜体混合*** |
| This | format | is | NOT MARKDOWN |
```

现在支持的格式可以参考： <http://xianbai.me/learn-md/article/extension/table.html>

至于单元格的 居中、右对齐…… 能够实现，但是懒得做了
