### ISSUE TITLE
HyperMD + react-codemirror

### ISSUE THREAD

**Issue by cgestes** [laobubu/HyperMD#26]
Hi guys,

Thank you for this awesome project.

As I was saying in https://github.com/laobubu/HyperMD/issues/21 I cannot get HyperMD (the typescript version) to work with react-codemirror.

I made a really simple test case to investigate but I couldn't find the issue.

Demo:
https://github.com/cgestes/react-hypermd-demo

Any idea how I can find what is wrong with this demo?

**Comment by laobubu** [comment]
Have you tried `mode: "hypermd"` ?
If still not working, I'll check it tomorrow

**Comment by laobubu** [comment]
Looks like *react-codemirror* 's build has a outdated CodeMirror inside (see https://github.com/JedWatson/react-codemirror/tree/master/dist ), which lacks some features to support HyperMD.

Try setting `<ReactCodeMirror>`'s prop `codeMirrorInstance` to `require("codemirror")`

**Comment by cgestes** [comment]
I'll try and keep you posted, thank you ;)

**Comment by cgestes** [comment]
Thank you for the leads.

Here are the results:
- setting mode to `hypermd` doesnt work.
- setting the codemirror instance to codemirror v5.38 doesnt help
- deduplicating codemirror only v5.38 (just in case) doesnt help

(I added to commit to force codemirror version)

Any new ideas?

**Comment by cgestes** [comment]
Got it to work...

It does work with the npm published version, but not when using yarn link.

**Comment by cgestes** [comment]
nailed it... 

The issue was a duplication of the codemirror instance when using yarn link.

I fixed it by putting codemirror in `peerDependencies` instead of `dependencies`.

**Comment by cgestes** [comment]
I guess we can close this one.

**Comment by cgestes** [comment]
see https://github.com/laobubu/HyperMD/pull/27
