### ISSUE TITLE
Suggestion: have ability to render heading (h1, h2, ...) in gutter to avoid offsetting them

### ISSUE THREAD

**Issue by nokola** [laobubu/HyperMD#28]
I really like the new mode where the bold, etc markers (the star * symbols) appear without offsetting the text.
Here's a suggestion of how to do similar improvement for headings: add whitespace to the left, then paint the "##" symbols there (perhaps a hack with codemirror's renderline() or something else?)

![image](https://user-images.githubusercontent.com/6869225/40632997-4d2ff6a8-62a1-11e8-8683-849246f61d63.png)

What do you think?

**Comment by laobubu** [comment]
You may modify the theme style to implement this. 

Download the patch: [issue28.diff](https://github.com/laobubu/HyperMD/files/2046833/issue28.diff.txt)

I'm not sure if this can be merged into master. Pro: no offset. Con: (maybe) too many blank.


![video_2018-05-29_132447](https://user-images.githubusercontent.com/1373914/40639543-14408012-6344-11e8-852c-7db423d8e3a5.gif)

-------

Or use gutter. I made a sketch and it looks weird.
![default](https://user-images.githubusercontent.com/1373914/40638967-dd5d4862-6340-11e8-8913-0eafe5cc1f5d.png)

**Comment by nokola** [comment]
Thanks! the patch works well! I also prefer the first version with space instead of gutter.
The blank space is OK for some cases, it's good to have the option.
