### ISSUE TITLE
能支持到Google Keep上吗

### ISSUE THREAD

**Issue by DingSoung** [laobubu/HyperMD#3]

**Comment by laobubu** [comment]
TLDR: HyperMD 不能，但是我的另外一个项目 [MarkdownIME](http://laobubu.net/MarkdownIME/) 能。

打开 MarkdownIME 项目主页，其中“不用安装任何插件就能使用”那里的 Magic Bookmarklet，可以用于 Google Keep。

HyperMD 是“纯文本编辑器”， Google Keep 不是纯文本记事本，因此需要的是一个“Markdown输入法”
