### ISSUE TITLE
Line is not highlighted with Shift+Up if it ends with bold text

### ISSUE THREAD

**Issue by michaelgmcd** [laobubu/HyperMD#38]
See demo below:

![hypermd-highlight-bug](https://user-images.githubusercontent.com/8161781/43009995-37cc654a-8c0d-11e8-92c9-13d5bffb9f8f.gif)

I would be interested in contributing. Not sure where to start with this though.

**Comment by laobubu** [comment]
This issue is Chrome-only. Can't reproduce in Firefox or Edge.
I will investigate. My intuition told me that this could be a difficult CodeMirror internal problem. 🤒

**Comment by laobubu** [comment]
Seems fixed. Will publish in few minutes

**Comment by michaelgmcd** [comment]
Awesome! Thanks

**Comment by laobubu** [comment]
Due to [a recent eslint incident](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes), all existing npm tokens [were automatically revoked](https://status.npmjs.org/incidents/dn7c1fgrr7ng).

HyperMD v0.3.10 was finally published just now.
