### ISSUE TITLE
Bold followed by a hyphen on the next line becomes a header

### ISSUE THREAD

**Issue by michaelgmcd** [laobubu/HyperMD#42]
I'm hoping these issues will turn more into PR's as I become familiar with HyperMD, but I've found another weird bug that I'm not sure what the cause is:

![bold-header-bug](https://user-images.githubusercontent.com/8161781/43119400-39b250f2-8ee4-11e8-9642-5334cf920ad1.gif)

**Comment by laobubu** [comment]
HyperMD's Markdown Parser is based on CodeMirror's Markdown Mode.
Just confirmed that CodeMirror has the same problem. [Demo Here.](https://codemirror.net/mode/markdown/index.html)

You can [submit this issue to CodeMirror](https://github.com/codemirror/CodeMirror/issues)

**Comment by laobubu** [comment]
According to CommonMark Spec, this is expected behavior (see https://spec.commonmark.org/0.28/#example-52 )

You can add an empty line between a list and a normal paragraph.
