### ISSUE TITLE
[BUG] underline style header does not appear in TOC

### ISSUE THREAD

**Issue by ZeppLu** [laobubu/HyperMD#46]
I tried on [https://laobubu.net/HyperMD/#./docs/zh-CN/README.md](https://laobubu.net/HyperMD/#./docs/zh-CN/README.md) with the following text:

```
# 1

1.1
------

## 1.2
```

The result is:
![image](https://user-images.githubusercontent.com/17007549/43637774-d4096264-9748-11e8-8f3f-436d8c8c60e6.png)

**Comment by laobubu** [comment]
The **current** TOC-generating script is just a **~~too young~~ too simple toy** for demo page. It's not even included in HyperMD package.

Feel free to modify [demo/toc.js](https://github.com/laobubu/HyperMD/blob/master/demo/toc.js) and submit a pull request.

Or wait for an official TOC extractor script. (It will be provided as one of [HyperMD goods](https://github.com/laobubu/HyperMD/blob/master/docs/goods.md) )

**Comment by ZeppLu** [comment]
~~I'm too naïve to do this,~~ look forward to next release
