### ISSUE TITLE
Supporting syntax highlight for code block

### ISSUE THREAD

**Issue by garaemon** [laobubu/HyperMD#69]
Is it possible to highlight the code block taking into account the syntax of programming languages?

**Comment by niemes** [comment]
yes, HyperMD use codemirror for that.

simple use : 3 ` ` ` without the space like on github

``` javascript
"let foo =  (bara) => return 'kooda'"
console.log(kooda)
```

**Comment by garaemon** [comment]
Is it possible to specify the name of the programming language which is used in the code block like `ruby` in the following example?

<pre>
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</pre>

**Comment by niemes** [comment]
Yes ofcourse, you can check the supported languages here : https://codemirror.net/mode/

Here an example of highlighting using hypermd codeblock with your code example : 

![hypermd_ruby](https://user-images.githubusercontent.com/6246777/91016109-88e56900-e5ec-11ea-8f45-f14962f9590d.png)


```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```

** You need to import/add all the codemirror mode and you can also change the css of the syntax highlighting.

**Comment by garaemon** [comment]
Thanks, 

I confirmed that on [the online HyperMD demo](https://laobubu.net/HyperMD/#README.md).

![スクリーンショット 2020-08-25 17 31 37](https://user-images.githubusercontent.com/40454/91151682-f5e62500-e6f8-11ea-8bc6-db58870f82e7.png)
