### ISSUE TITLE
Sometimes Ctrl+A shortcut does not cover all the text

### ISSUE THREAD

**Issue by menou2u** [laobubu/HyperMD#8]
I've found a scenario where Ctrl+A does not cover all the text. See below :
Here is a text without any style. Ctrl+A renders well.
![image](https://user-images.githubusercontent.com/22363736/27901700-53560276-6233-11e7-8fc4-fc3a28b4d2cd.png)

After adding a first style to the text (**), Ctrl+A does not cover the first line anymore.
![image](https://user-images.githubusercontent.com/22363736/27904664-b6c2ead6-623d-11e7-99d2-164115ae15aa.png)

However, Ctrl+A considered the whole text anyway. E.g.: If I want to delete the whole text here is the result:
![image](https://user-images.githubusercontent.com/22363736/27904700-dc5b8744-623d-11e7-9594-eb1267172ce5.png)

So it seems to "just" be a display bug.

**Comment by laobubu** [comment]
Hmmm, this
